language: node_js
node_js:
- '9'
install:
- npm install
script: tsc
deploy:
  provider: heroku
  api_key:
    secure: h9Z+g9cDAi2OVK/WXmSdwywTp3PffavSeuSMYrXQl0vAJdcd0YHmZ0qJUXEwrMRcMPVelAxPHhYRUpFxiMrxiUvvuyawCal3U7ODiEIeZQWhbcPiWi/OtqqeRlvEqKmR0KDM87Dv2TEIWIOo2yJ7N9GgEKTVM6NlggHaW5RjpvTA8D7mM7zCVLGZw06ufswwkeZw3vuuM2dKUUfbyps9lp1v7+kEqKrKC8LUdsPe2tGP3YDSlbX6WKN/GUmieaxPk88cnk3a7woJQ9J8C2lAt0RMD5958wXV1jZDxoyfNK8I4mSj+OB2Uu/BbOQ6nxGZjxk9l42+iMT6pst/c/ZBNjqmxuA6iuLJzJ81RY1LyGiMhthk02JkhVd8h1QOSt8Q76lk4HKOpaiL+vo9hkOOzb6DwHyDTr9ECN/k4Ubl64rvXQg1xt5tkDY9F2G/LIoT6B5uVdCbBNWleUy4d11bDk0GdLji3kP7YIve9/ytfxH8BwSsBwYlpe+0kuc+eV0kukx7bDrACAs0yzOzKCnvcsTufMQwgfXxC+7hS9hvuHdGySAFzSFix2f8OToAsPIau31zMgZkS+JCgwf7e0sZ5segT/+YOLP8SGqwHH/TvuMJtL2gtVtNj+YJhYx4x9ylY2bBhqDx86uea3NG06pQNKrQFqxqQQErNQLh5+I9vnM=
  app: pocketDoc
  on:
    repo: judahh/pocketDoc
